language: go

env:
  global:
    - VERSION="${TRAVIS_TAG:=0.0_git$(date +%Y%m%d)-1}"
    - PKG_URL="http://example.com"
    - PKG_DESC="Simple hello app"
    - PKG_MAINT="John Doe <john.dow@example.com>"
    - PKG_LICNS="MIT"
  matrix:
    - NAME=john
    - NAME=jane

before_deploy:
  - gem install fpm --no-document
  - make pkg
  - sed -i -e "s/\$VERSION/$VERSION/" bintray-pkg.json
  - sed -i -e "s/\$DATE/$(date +%Y-%m-%d)/" bintray-pkg.json
  - sed -i -e "s/\$NAME/$NAME/" bintray-pkg.json
  - cat bintray-pkg.json

deploy:
  # "production" deploy
  - provider: bintray
    user: suntong
    key: $BINTRAY_API_KEY
    file: bintray-pkg.json
    skip_cleanup: true
    on:
      tags: true

  # "staging" deploy
  - provider: bintray
    user: suntong
    key: $BINTRAY_API_KEY
    file: bintray-pkg.json
    skip_cleanup: true
    on:
      branch: master
