language: go

go:
- 1.7.5
- 1.8rc3

env:
  matrix:
  - NAME=john
  - NAME=jane

before_deploy:
  - gem install fpm --no-document
  - make pkg
  - sed -i'' -e "s/\$VERSION/${TRAVIS_TAG:=0.0.0}/" descriptor.json
  - sed -i'' -e "s/\$DATE/$(date +%Y-%m-%d)/" descriptor.json

deploy:
  # "production" deploy
  - provider: bintray
    user: suntong
    key: $BINTRAY_API_KEY
    file: descriptor.json
    skip_cleanup: true
    on:
      go: 1.7.5
      tags: true

  # "staging" deploy
  - provider: bintray
    user: suntong
    key: $BINTRAY_API_KEY
    file: descriptor.json
    skip_cleanup: true
    on:
      go: 1.7.5
      branch: master
