language: go

go:

env:
  matrix:
  - NAME=john
  - NAME=jane

before_deploy:
  - gem install fpm --no-document
  - make pkg
  - sed -i -e "s/\$VERSION/${TRAVIS_TAG:=0.0_git$(date +%Y%m%d)-1}/" bintray-pkg.json
  - sed -i -e "s/\$DATE/$(date +%Y-%m-%d)/" bintray-pkg.json
  - sed -i -e "s/\$NAME/$NAME/" bintray-pkg.json
  - cat bintray-pkg.json

deploy:
  # "production" deploy
  - provider: bintray
    user: suntong
    key: $BINTRAY_API_KEY
    file: bintray-pkg.json
    skip_cleanup: true
    on:
      tags: true

  # "staging" deploy
  - provider: bintray
    user: suntong
    key: $BINTRAY_API_KEY
    file: bintray-pkg.json
    skip_cleanup: true
    on:
      branch: master
