language: go

go:

env:
  matrix:
  - NAME=john
#  - NAME=jane

before_deploy:
  - gem install fpm --no-document
  - make pkg
  - sed -i'' -e "s/\$VERSION/${TRAVIS_TAG:=0.0.0}/" bintray.json
  - sed -i'' -e "s/\$DATE/$(date +%Y-%m-%d)/" bintray.json

deploy:
  # "production" deploy
  - provider: bintray
    user: suntong
    key: $BINTRAY_API_KEY
    file: bintray.json
    skip_cleanup: true
    on:
      tags: true

  # "staging" deploy
  - provider: bintray
    user: suntong
    key: $BINTRAY_API_KEY
    file: bintray.json
    skip_cleanup: true
    on:
      branch: master
